---
title: "Stl Lead Inequity"
author: "Grace Lewin"
date: "8/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

```{r}
stl_lead <- read_delim(here::here("data", "stl_blood_lead.csv"), delim = ";")
```

```{r}
summary(stl_lead)

dim(stl_lead)

skimr::skim(stl_lead)

names(stl_lead)

stl_lead <- stl_lead %>% clean_names() 
```

```{r}
stl_lead_prop <- stl_lead %>% 
  mutate(prop_white = (white/total_pop)*100) %>% 
  mutate(pct_elevated = str_replace(pct_elevated,
                                    pattern = ",",
                                    replacement = ".")) %>% 
  mutate(pct_elevated = as.numeric(pct_elevated))
```

```{r stl_lead_plot, fig.height = 3, fig.width = 4}
stl_lead_plot <- ggplot(data = stl_lead_prop, aes(x = prop_white, y = pct_elevated)) +
  geom_point(aes(size = prop_white), 
             alpha = 0.5,
             color = "orange")

stl_lead_plot 

ggsave(here::here("figs", "stl_lead_plot.png"), plot = stl_lead_plot, 
                  width = 6, height = 5)
```

The general trend in this graph is that in census tracts with a higher proportion of white children, there is a lower percentage of elevated blood lead levels. 

```{r pct_elevated_hist, fig.height = 4, fig.width = 6}
pct_elevated_hist <- ggplot(data = stl_lead_prop, aes(x = pct_elevated)) +
  geom_histogram(color = "blue", fill = "pink", size = .5) +
  labs(title = "Histogram of Percent Elevated Blood Lead Levels", x = "Percent Elevated Blood Lead Levels", y = "Count")

pct_elevated_hist

ggsave(here::here("figs", "pct_elevated_hist.jpg"), plot = pct_elevated_hist, width = 8, height = 6)
```



